version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=stationSki
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
      interval: 5s
      timeout: 3s
      retries: 10

  app-skier:
    depends_on:
      mysqldb:
        condition: service_healthy
    image: walidkhrouf/skier-app:1.0.0
    restart: unless-stopped
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysqldb:3306/stationSki?createDatabaseIfNotExist=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&connectTimeout=30000"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "rootpassword"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SERVER_SERVLET_CONTEXT_PATH: "/api"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8089/api/actuator/health || exit 1"]
      interval: 15s
      timeout: 15s
      retries: 10
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: '1'

volumes:
  db: