version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword  # Changed from empty to secure password
      - MYSQL_DATABASE=stationSki
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
      interval: 5s
      timeout: 3s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  app-skier:
    depends_on:
      mysqldb:
        condition: service_healthy
    image: walidkhrouf/skier-app:1.0.0
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/stationSki?createDatabaseIfNotExist=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10",
        "spring.datasource.username": "root",
        "spring.datasource.password": "rootpassword",
        "spring.datasource.hikari.connection-timeout": 30000,
        "spring.jpa.hibernate.ddl-auto": "update",
        "server.servlet.context-path": "/api",
        "spring.mvc.format.date": "yyyy-MM-dd",
        "management.endpoint.health.show-details": "always"
      }'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8089/api/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 768M
          cpus: '1'
    stdin_open: true
    tty: true

volumes:
  db:
